# docker-compose.yml
services:
  soc_analyzer:
    build: .
    container_name: soc_analyzer_app
    env_file:
      - .env
    volumes:
      - ./reports:/app/reports
      - /tmp/.X11-unix:/tmp/.X11-unix
      # FIX: This line now correctly maps your computer's root directory (/)
      # to the /scannable_files folder in the container.
      - /:/scannable_files
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

